# version est√° obsoleto en Docker Compose v2+ y se ignora

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus-rule.yml:/etc/prometheus/rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    networks:
      - monitoring

  # Descomenta cuando exista la carpeta api-reservations
  # api-users:
  #   build: ./api-reservations
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - monitoring

  # Descomenta cuando exista la carpeta api_payments
  # api-orders:
  #   build: ./api_payments
  #   ports:
  #     - "8001:8001"
  #   networks:
  #     - monitoring

  api-inventory:
    build: ./microservicio_inventario
    ports:
      - "8002:8000"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
