global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # microservicio 1
  - job_name: 'api-users'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-users:8000']

  # microservicio 1
  - job_name: 'api-orders'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-orders:8000']
