global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # # microservicio 1
  # - job_name: 'api-reservations'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['api-users:8000']

  # # microservicio 2
  # - job_name: 'api-payments'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['api-orders:8000']

  # microservicio inventario (activo)
  - job_name: 'api-inventory'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-inventory:8000']

rule_files:
  - /etc/prometheus/rules.yml
